services:
  traefik:
    image: traefik:v3.3
    secrets:
      - traefik_auth
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.swarm=true"
      - "--providers.swarm.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--providers.file.filename=/etc/traefik/traefik_dynamic.yml"
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/traefik/certs:/certs:ro
      - ./configs/traefik_dynamic.yml:/etc/traefik/traefik_dynamic.yml:ro
    networks:
      - traefik-public
      - monitoring
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.updspace.com`)"
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard.tls=true"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager

  prometheus:
    image: prom/prometheus:latest
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
        mode: 0444
    ports:
      - target: 9090
        published: 9090
        protocol: tcp
        mode: host
    networks:
      monitoring:
        aliases:
          - prometheus
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.updspace.com`)"
      - "traefik.http.routers.prometheus.entrypoints=websecure"
      - "traefik.http.routers.prometheus.tls=true"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"

  grafana:
    image: grafana/grafana:latest
    configs:
      - source: grafana_config
        target: /etc/grafana/grafana.yml
        mode: 0444
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    networks:
      monitoring:
        aliases:
          - grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD_FILE=/run/secrets/grafana_admin_password
    secrets:
      - grafana_admin_password
    volumes:
      - grafana_data:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.updspace.com`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

networks:
  traefik-public:
    external: true
  monitoring:
    driver: overlay
    attachable: true

configs:
  traefik_dynamic:
    file: ./configs/traefik_dynamic.yml
  prometheus_config:
    file: ./configs/prometheus.yml
  grafana_config:
    file: ./configs/grafana.ini

volumes:
  grafana_data:

secrets:
  grafana_admin_password:
    external: true
  traefik_auth:
    external: true
