services:
  traefik:
    image: traefik:v3.3
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.swarm=true"
      - "--providers.swarm.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--providers.file.filename=/etc/traefik/traefik_dynamic.yml"
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
    configs:
      - source: traefik_dynamic
        target: /etc/traefik/traefik_dynamic.yml
        mode: 0444
    secrets:
      - tls_cert
      - tls_key
    networks:
      - traefik-public
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.updspace.com`)"
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard.tls=true"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"

  prometheus:
    image: prom/prometheus:latest
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
        mode: 0444
    ports:
      - target: 9090
        published: 9090
        protocol: tcp
        mode: host
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    networks:
      - monitoring
    environment:
      - GF_SECURITY_ADMIN_PASSWORD_FILE=/run/secrets/grafana_admin_password
    secrets:
      - grafana_admin_password
    volumes:
      - grafana_data:/var/lib/grafana

networks:
  traefik-public:
    external: true
  monitoring:
    external: true

configs:
  traefik_dynamic:
    file: ./configs/traefik_dynamic.yml
  prometheus_config:
    file: ./configs/prometheus.yml

volumes:
  grafana_data:

secrets:
  tls_cert:
    external: true
  tls_key:
    external: true
  grafana_admin_password:
    external: true
