apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: id
      namespace: updspace-id
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: test
        path: /spec/template/spec/containers/2/name
        value: mutations
      - op: replace
        path: /spec/template/spec/containers/2/image
        value: docker.io/updspace/id-observability@sha256:d8f239a8641a12bfaa01ded7a1798d7b083ab1ff3edf6d02037870ca4b0a0cd3
  - target:
      group: batch
      version: v1
      kind: CronJob
      namespace: updspace-id
    patch: |-
      - op: replace
        path: /spec/suspend
        value: false
