apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: caddy-to-uptime-kuma
  namespace: edge
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: caddy
  policyTypes: [Egress]
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: uptime-kuma
          podSelector:
            matchLabels:
              app.kubernetes.io/name: uptime-kuma
      ports:
        - protocol: TCP
          port: 3001
