services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    networks:
      monitoring:
        aliases:
          - grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD_FILE=/run/secrets/grafana_admin_password
    secrets:
      - grafana_admin_password
    volumes:
      - grafana_data:/var/lib/grafana

networks:
  monitoring:
    external: true

volumes:
  grafana_data:

secrets:
  grafana_admin_password:
    external: true
