tls:
  certificates:
    - certFile: "/certs/updspace.com.cloudflare-origin.crt"
      keyFile: "/certs/updspace.com.cloudflare-origin.key"
  domains:
    - main: "updspace.com"
      sans:
        - "updspace.com"
        - "*.updspace.com"