tls:
  certificates:
    - certFile: "/certs/cloudflare-origin.crt"
      keyFile: "/certs/cloudflare-origin.key"

http:
  routers:
    prometheus:
      rule: "Host(`prometheus.updspace.com`)"
      entryPoints:
        - websecure
      service: prometheus-service
      tls: {}

    grafana:
      rule: "Host(`grafana.updspace.com`)"
      entryPoints:
        - websecure
      service: grafana-service
      tls: {}

  services:
    prometheus-service:
      loadBalancer:
        servers:
          - url: "http://prometheus:9090"

    grafana-service:
      loadBalancer:
        servers:
          - url: "http://grafana:3000"
