http:
  routers:
    prometheus:
      rule: "Host(`prometheus.updspace.com`)"
      service: prometheus-service
      entryPoints:
        - websecure
      tls:
        certResolver: myresolver
    grafana:
      rule: "Host(`grafana.updspace.com`)"
      service: grafana-service
      entryPoints:
        - websecure
      tls:
        certResolver: myresolver

  services:
    prometheus-service:
      loadBalancer:
        servers:
          - url: "http://prometheus:9090"
    grafana-service:
      loadBalancer:
        servers:
          - url: "http://grafana:3000"
